### ISSUE TITLE
Can't install_github()?

### ISSUE THREAD

**Issue by Kenkleinman** [dtkaplan/checkr-v-0.1#7]
Message:

>    install_github("dtkaplan/checkr")
> Downloading GitHub repo dtkaplan/checkr@master
> from URL https://api.github.com/repos/dtkaplan/checkr/zipball/master
> Installing checkr
> Installation failed: cannot open the connection
> Warning messages:
> 1: In normalizePath(path) :
>   path[1]="/home/docker/hms_0.3.tar.gz": No such file or directory
> 2: In read.dcf(path) :
>   cannot open compressed file '/home/docker/hms_0.3.tar.gz/DESCRIPTION', probable reason 'No such file or directory'
>

**Comment by nicholasjhorton** [comment]
I was able to install on a Mac running R version 3.4.0.
Can you install other packages using install_github()?

**Comment by Kenkleinman** [comment]
Yup, checked before I posted :-)

**Comment by nicholasjhorton** [comment]
Can you please include the output of sessionInfo()?

All the best,

Nick

**Comment by Kenkleinman** [comment]
Most confusingly, it installed on this fifth try.
